spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        routes:
          - id: task-service
            url: lb://task-service
            predicates:
              - Path=/api/v1/tasks/**
          - id: user-service
              - url: lb://user-service
              - predicates:
              - Path=/api/v1/users/**
server:
  port: 8080